# Template for Cloudflare API token secret
# Replace YOUR_CLOUDFLARE_API_TOKEN with your actual Cloudflare API token
# The token needs Zone:Read and DNS:Edit permissions for marsem.org

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: kafka-tool
type: Opaque
stringData:
  api-token: "YOUR_CLOUDFLARE_API_TOKEN"

---
# Instructions:
# 1. Go to https://dash.cloudflare.com/profile/api-tokens
# 2. Create a token with:
#    - Zone:Read permissions for marsem.org
#    - DNS:Edit permissions for marsem.org
# 3. Replace YOUR_CLOUDFLARE_API_TOKEN above with the actual token
# 4. Apply this file: kubectl apply -f cloudflare-secret-template.yaml
