apiVersion: v1
kind: Namespace
metadata:
  name: kafka-tool
  labels:
    name: kafka-tool
    app: kafka-web-app-v2
    environment: production
  annotations:
    description: "Kafka Web App v2 - Enterprise Kafka Management Tool"
    owner: "marsem.org"
    version: "2.0.0"
