apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-static-files
  namespace: kafka-tool
  labels:
    app: kafka-web-app-v2
    component: frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kafka Web Tool v2</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container {
                text-align: center;
                color: white;
                padding: 2rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
                border: 1px solid rgba(255, 255, 255, 0.2);
            }
            h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                font-weight: 300;
            }
            .subtitle {
                font-size: 1.2rem;
                margin-bottom: 2rem;
                opacity: 0.9;
            }
            .status {
                background: rgba(76, 175, 80, 0.2);
                border: 1px solid rgba(76, 175, 80, 0.5);
                border-radius: 10px;
                padding: 1rem;
                margin: 1rem 0;
            }
            .api-links {
                margin-top: 2rem;
            }
            .api-links a {
                color: #fff;
                text-decoration: none;
                background: rgba(255, 255, 255, 0.2);
                padding: 0.5rem 1rem;
                border-radius: 5px;
                margin: 0 0.5rem;
                display: inline-block;
                transition: background 0.3s;
            }
            .api-links a:hover {
                background: rgba(255, 255, 255, 0.3);
            }
            .version {
                margin-top: 2rem;
                font-size: 0.9rem;
                opacity: 0.7;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Kafka Web Tool v2</h1>
            <div class="subtitle">Modern Kafka Management Interface</div>
            
            <div class="status">
                <strong>✅ Application Status: Running</strong><br>
                Backend services are operational and ready to accept connections.
            </div>
            
            <div class="api-links">
                <a href="/api/v1/health" target="_blank">Health Check</a>
                <a href="/api/v1/swagger-ui.html" target="_blank">API Documentation</a>
                <a href="/api/v1/connections" target="_blank">Connections API</a>
            </div>
            
            <div class="version">
                Version 2.0.0 | Deployed on Kubernetes<br>
                <small>React frontend coming soon...</small>
            </div>
        </div>

        <script>
            // Simple health check
            fetch('/api/v1/health')
                .then(response => response.json())
                .then(data => {
                    console.log('Backend health:', data);
                    if (data.status === 'UP') {
                        document.querySelector('.status').innerHTML = 
                            '<strong>✅ Application Status: ' + data.status + '</strong><br>' +
                            'Backend services are operational. Version: ' + data.version;
                    }
                })
                .catch(error => {
                    console.log('Backend health check failed:', error);
                    document.querySelector('.status').innerHTML = 
                        '<strong>⚠️ Application Status: Frontend Only</strong><br>' +
                        'Backend services may be starting up...';
                });
        </script>
    </body>
    </html>
